import type {
  HostType,
  ProjectFile,
} from '@house-technical-designer/core-domain';
import {
  entityCollisions,
  hostAccepts,
  isTextNote,
  levelHosts,
  localCollisions,
  projectEntities,
  validateTextNote,
} from '@house-technical-designer/core-domain';
import validateProjectSchema from './generated-project-validator.js';
import {
  DEFAULT_PROJECT_MIGRATIONS,
  runMigrationChain,
  type MigrationJournalEntry,
  type ProjectMigration,
} from './migrations.js';

export const CURRENT_PROJECT_SCHEMA_VERSION = '1.1.0';

/**
 * Bounds an imported file has to respect.
 *
 * A project file arrives from outside the application: it may be corrupt,
 * generated by another tool, or simply enormous. The limits refuse such a file
 * with a message naming what is out of bounds, rather than letting the browser
 * freeze partway through drawing it. They are deliberately far above any real
 * house — a plausible dwelling uses a fraction of a percent of them.
 */
export interface ProjectImportLimits {
  /** Size of the JSON text, in characters. */
  readonly maximumCharacters: number;
  readonly maximumLevels: number;
  readonly maximumWalls: number;
  readonly maximumOpenings: number;
  readonly maximumSpaces: number;
  readonly maximumMaterials: number;
  readonly maximumNetworkNodes: number;
  readonly maximumNetworkEdges: number;
}

export const DEFAULT_PROJECT_IMPORT_LIMITS: ProjectImportLimits = {
  maximumCharacters: 32_000_000,
  maximumLevels: 50,
  maximumWalls: 20_000,
  maximumOpenings: 20_000,
  maximumSpaces: 5_000,
  maximumMaterials: 5_000,
  maximumNetworkNodes: 50_000,
  maximumNetworkEdges: 50_000,
};

/** What exceeded its bound, so the message can name it rather than say "too big". */
export interface ProjectLimitBreach {
  readonly limit: keyof ProjectImportLimits;
  readonly label: string;
  readonly actual: number;
  readonly maximum: number;
}

export interface ProjectValidationIssue {
  readonly path: string;
  readonly message: string;
}
export type ProjectLoadResult =
  | {
      readonly status: 'OK';
      readonly file: ProjectFile;
      readonly migrationJournal: readonly MigrationJournalEntry[];
    }
  | { readonly status: 'INVALID_JSON'; readonly message: string }
  | {
      readonly status: 'INVALID_PROJECT';
      readonly issues: readonly ProjectValidationIssue[];
    }
  | {
      readonly status: 'UNSUPPORTED_FUTURE_SCHEMA';
      readonly schemaVersion: string;
    }
  | { readonly status: 'MIGRATION_ERROR'; readonly message: string }
  | { readonly status: 'TOO_LARGE'; readonly breach: ProjectLimitBreach };

export function loadProjectJson(
  source: string,
  migrations: readonly ProjectMigration[] = DEFAULT_PROJECT_MIGRATIONS,
  limits: ProjectImportLimits = DEFAULT_PROJECT_IMPORT_LIMITS,
): ProjectLoadResult {
  if (source.length > limits.maximumCharacters)
    return {
      status: 'TOO_LARGE',
      breach: {
        limit: 'maximumCharacters',
        label: 'caractères',
        actual: source.length,
        maximum: limits.maximumCharacters,
      },
    };
  let value: unknown;
  try {
    value = JSON.parse(source) as unknown;
  } catch (error: unknown) {
    return {
      status: 'INVALID_JSON',
      message: error instanceof Error ? error.message : 'Invalid JSON.',
    };
  }
  if (!isRecord(value) || typeof value.schemaVersion !== 'string') {
    const issues = validateProjectFile(value);
    return { status: 'INVALID_PROJECT', issues };
  }
  if (!/^\d+\.\d+\.\d+$/u.test(value.schemaVersion)) {
    return {
      status: 'INVALID_PROJECT',
      issues: [
        { path: '/schemaVersion', message: 'must be semantic version x.y.z' },
      ],
    };
  }
  if (compareSemver(value.schemaVersion, CURRENT_PROJECT_SCHEMA_VERSION) > 0) {
    return {
      status: 'UNSUPPORTED_FUTURE_SCHEMA',
      schemaVersion: value.schemaVersion,
    };
  }
  let migrationJournal: readonly MigrationJournalEntry[] = [];
  if (value.schemaVersion !== CURRENT_PROJECT_SCHEMA_VERSION) {
    const migrated = runMigrationChain(
      value,
      CURRENT_PROJECT_SCHEMA_VERSION,
      migrations,
    );
    if (migrated.status !== 'OK') {
      return {
        status: 'MIGRATION_ERROR',
        message:
          migrated.status === 'MIGRATION_NOT_FOUND'
            ? `No migration path from ${migrated.from} to ${migrated.target}.`
            : `${migrated.migrationId}: ${migrated.message}`,
      };
    }
    value = migrated.value;
    migrationJournal = migrated.journal;
  }
  const issues = validateProjectFile(value);
  if (issues.length > 0) return { status: 'INVALID_PROJECT', issues };
  const file = value as ProjectFile;
  const breach = exceededLimit(file, limits);
  if (breach !== undefined) return { status: 'TOO_LARGE', breach };
  return { status: 'OK', file: structuredClone(file), migrationJournal };
}

/** The first bound the file exceeds, counted on the validated model. */
export function exceededLimit(
  file: ProjectFile,
  limits: ProjectImportLimits = DEFAULT_PROJECT_IMPORT_LIMITS,
): ProjectLimitBreach | undefined {
  const levels = file.project.building.levels;
  const networks = file.project.systems ?? [];
  const counts: readonly {
    readonly limit: keyof ProjectImportLimits;
    readonly label: string;
    readonly actual: number;
  }[] = [
    { limit: 'maximumLevels', label: 'niveaux', actual: levels.length },
    {
      limit: 'maximumWalls',
      label: 'murs',
      actual: total(levels, ({ walls }) => walls.length),
    },
    {
      limit: 'maximumOpenings',
      label: 'ouvertures',
      actual: total(levels, ({ openings }) => openings.length),
    },
    {
      limit: 'maximumSpaces',
      label: 'pièces',
      actual: total(levels, ({ spaces }) => spaces.length),
    },
    {
      limit: 'maximumMaterials',
      label: 'matériaux',
      actual: file.project.materialLibrary?.materials.length ?? 0,
    },
    {
      limit: 'maximumNetworkNodes',
      label: 'nœuds de réseau',
      actual: total(networks, ({ nodes }) => nodes.length),
    },
    {
      limit: 'maximumNetworkEdges',
      label: 'tronçons de réseau',
      actual: total(networks, ({ edges }) => edges.length),
    },
  ];
  for (const count of counts) {
    const maximum = limits[count.limit];
    if (count.actual > maximum) return { ...count, maximum };
  }
  return undefined;
}

function total<T>(items: readonly T[], size: (item: T) => number): number {
  return items.reduce((sum, item) => sum + size(item), 0);
}

/** Validates with the compiled canonical JSON Schema, then checks project-wide references. */
export function validateProjectFile(
  value: unknown,
): readonly ProjectValidationIssue[] {
  if (!validateProjectSchema(value))
    return (validateProjectSchema.errors ?? []).map((error) => ({
      path:
        error.keyword === 'required' &&
        typeof error.params.missingProperty === 'string'
          ? `${error.instancePath}/${error.params.missingProperty}`
          : error.instancePath === ''
            ? '/'
            : error.instancePath,
      message: error.message ?? 'does not satisfy the project schema',
    }));
  return validateProjectReferences(value as ProjectFile);
}

/**
 * References and containment, checked across the whole project.
 *
 * A reference that names something absent is a broken file; so is an object
 * stored in a container it does not belong to. An opening whose wall exists on
 * another level passes a "the wall exists" test and still describes a house
 * nobody can build, so containment is checked, not only existence.
 */
export function validateProjectReferences(
  file: ProjectFile,
): readonly ProjectValidationIssue[] {
  const issues: ProjectValidationIssue[] = [];
  const levels = new Set(file.project.building.levels.map(({ id }) => id));
  const walls = new Set(
    file.project.building.levels.flatMap(({ walls }) =>
      walls.map(({ id }) => id),
    ),
  );
  const spaces = new Set<string>(
    file.project.building.levels.flatMap(({ spaces }) =>
      spaces.map(({ id }) => id as string),
    ),
  );
  const equipment = new Set(file.project.equipment?.map(({ id }) => id) ?? []);
  /** What a network node may be fixed to. */
  const hosts = new Set<string>([
    ...file.project.building.levels.flatMap(
      ({ walls, slabs, roofs, spaces: rooms, openings, components }) => [
        ...walls.map(({ id }) => id as string),
        ...slabs.map(({ id }) => id as string),
        ...roofs.map(({ id }) => id as string),
        ...rooms.map(({ id }) => id as string),
        ...openings.map(({ id }) => id as string),
        // A network node may stand for a thing placed in the building: the
        // radiator this pipe feeds, the luminaire this circuit lights.
        ...(components ?? []).map(({ id }) => id as string),
      ],
    ),
    ...(file.project.equipment?.map(({ id }) => id) ?? []),
  ]);
  /**
   * What a placed component may be physically fixed to.
   *
   * The same answer the editor gives, from the same registry. It used to be a
   * list written here — a wall, a slab, a roof plane — while the editor had
   * come to accept whole roofs, openings and other appliances. A command could
   * therefore produce a project this importer would refuse, which is a file
   * the application writes and cannot read back.
   *
   * A room is a volume and is named by `spaceId`; a catalogue entry is a
   * description and is named by `definitionId`. A node may be bound to far
   * more than any of this — it stands for what it feeds — and lending a
   * component the node's list is how a radiator ends up « fixed to » the model
   * of a radiator.
   */
  const supports = new Map<string, ReadonlySet<HostType>>();
  for (const level of file.project.building.levels)
    for (const [id, hosts] of levelHosts(level)) supports.set(id, hosts);
  /**
   * The level each object of the building belongs to.
   *
   * Every reference of a network node can exist on its own and the set still be
   * impossible: a node declared on the ground floor, sitting in a room upstairs
   * and fixed to a wall of a third level is three valid identifiers describing
   * a place that does not exist. Knowing where each object lives is what makes
   * that check possible — for every family the project holds, not for the six
   * somebody remembered.
   */
  const levelOfObject = new Map<string, string>();
  for (const { id, levelId } of projectEntities(file.project))
    if (levelId !== undefined) levelOfObject.set(id, levelId);
  // Identifiers are unique across the whole project, not merely inside their
  // own list. Selection, overlays, dimensions and scenario paths all address
  // objects by identifier alone; two objects sharing one would make a click
  // ambiguous and a scenario point at either of them.
  // One index of every identified object, for every part of the application
  // that addresses one. The list used to be written here, and it had fallen
  // seven families behind the model: a stair and a saved view could share an
  // identifier and nothing said so.
  for (const { id, entities } of entityCollisions(file.project))
    issues.push({
      path: `/project/${entities[0]!.path}`,
      message: `uses the identifier ${id} for more than one object: ${entities
        .map(({ family }) => family)
        .join(', ')}`,
    });
  for (const { id, entities } of localCollisions(file.project))
    issues.push({
      path: `/project/${entities[0]!.path}`,
      message: `declares the identifier ${id} more than once inside the same parent`,
    });
  const materials = new Set(
    file.project.materialLibrary?.materials.map(({ id }) => id) ?? [],
  );
  const assemblies = new Set(
    file.project.assemblies?.map(({ id }) => id) ?? [],
  );
  file.project.building.levels.forEach((level, levelIndex) => {
    const base = `/project/building/levels/${levelIndex}`;
    const levelWalls = new Set(level.walls.map(({ id }) => id));
    for (const [collection, elements] of [
      ['walls', level.walls],
      ['slabs', level.slabs],
      ['roofs', level.roofs],
    ] as const)
      elements.forEach((element, index) => {
        if (!levels.has(element.levelId))
          issues.push({
            path: `${base}/${collection}/${index}/levelId`,
            message: `references unknown level ${element.levelId}`,
          });
        else if (element.levelId !== level.id)
          issues.push({
            path: `${base}/${collection}/${index}/levelId`,
            message: `is stored on level ${level.id} but declares level ${element.levelId}`,
          });
        if (!assemblies.has(element.assemblyId))
          issues.push({
            path: `${base}/${collection}/${index}/assemblyId`,
            message: `references unknown assembly ${element.assemblyId}`,
          });
      });
    // A wall built to a storey above holds that storey's identifier and no
    // height of its own: naming a level the project does not hold leaves a
    // wall whose height nothing can answer.
    level.walls.forEach((wall, index) => {
      if (wall.heightMode !== 'TO_LEVEL') return;
      if (!levels.has(wall.topLevelId))
        issues.push({
          path: `${base}/walls/${index}/topLevelId`,
          message: `references unknown level ${wall.topLevelId}`,
        });
    });
    level.openings.forEach((opening, index) => {
      if (!walls.has(opening.hostElementId))
        issues.push({
          path: `${base}/openings/${index}/hostElementId`,
          message: `references unknown wall ${opening.hostElementId}`,
        });
      else if (!levelWalls.has(opening.hostElementId))
        issues.push({
          path: `${base}/openings/${index}/hostElementId`,
          message: `is stored on level ${level.id} but hosted by wall ${opening.hostElementId} of another level`,
        });
    });
    level.annotations.forEach((annotation, index) => {
      // A note says something to a human being; nothing in the model has to
      // agree with it, and it is refused only for being empty or unplaceable.
      if (isTextNote(annotation)) {
        for (const issue of validateTextNote(annotation))
          issues.push({
            path: `${base}/annotations/${index}/${issue.path}`,
            message: issue.message,
          });
        return;
      }
      // A dimension measures two wall endpoints; a dimension whose wall is
      // gone measures nothing, and the drawing would show a length nobody can
      // trace back to the model.
      for (const [side, reference] of [
        ['first', annotation.first],
        ['second', annotation.second],
      ] as const) {
        if (!walls.has(reference.wallId))
          issues.push({
            path: `${base}/annotations/${index}/${side}/wallId`,
            message: `references unknown wall ${reference.wallId}`,
          });
        else if (!levelWalls.has(reference.wallId))
          issues.push({
            path: `${base}/annotations/${index}/${side}/wallId`,
            message: `is stored on level ${level.id} but measures wall ${reference.wallId} of another level`,
          });
      }
    });
    // A thing placed in the building names what it stands for, where it hangs
    // and which room it is in. Each of those can be absent and the object
    // still be described; none of them may name something the project does
    // not hold.
    (level.components ?? []).forEach((component, index) => {
      const path = `${base}/components/${index}`;
      if (component.levelId !== level.id)
        issues.push({
          path: `${path}/levelId`,
          message: `is stored on level ${level.id} but declares level ${component.levelId}`,
        });
      if (
        component.definitionId !== undefined &&
        !equipment.has(component.definitionId)
      )
        issues.push({
          path: `${path}/definitionId`,
          message: `references unknown equipment ${component.definitionId}`,
        });
      if (component.spaceId !== undefined && !spaces.has(component.spaceId))
        issues.push({
          path: `${path}/spaceId`,
          message: `references unknown space ${component.spaceId}`,
        });
      if (
        component.hostObjectId !== undefined &&
        !supports.has(component.hostObjectId)
      )
        issues.push({
          path: `${path}/hostObjectId`,
          message: `references ${component.hostObjectId}, which is nothing a component can be fixed to`,
        });
      // What the file itself says this model may be fixed to. Read from the
      // project's own copy of the catalogue entry rather than from a
      // catalogue: a house has to open the same way in two years, when the
      // catalogue may have tightened a rule the house was drawn under.
      const allowed =
        component.definitionId === undefined
          ? undefined
          : file.project.equipment?.find(
              ({ id }) => id === component.definitionId,
            )?.allowedHosts;
      if (
        allowed !== undefined &&
        allowed.length > 0 &&
        component.hostObjectId !== undefined &&
        supports.has(component.hostObjectId) &&
        !hostAccepts(allowed, supports.get(component.hostObjectId))
      )
        issues.push({
          path: `${path}/hostObjectId`,
          message: `is fixed to ${component.hostObjectId}, which its own model does not accept: it goes on ${allowed.join(', ')}`,
        });
      // Each identifier can be real while the three together describe a place
      // that does not exist: a radiator on the ground floor, in a bedroom
      // upstairs, fixed to a wall of a third storey.
      for (const [key, reference] of [
        ['spaceId', component.spaceId],
        ['hostObjectId', component.hostObjectId],
      ] as const) {
        if (reference === undefined) continue;
        const objectLevel = levelOfObject.get(reference);
        if (objectLevel === undefined || objectLevel === component.levelId)
          continue;
        issues.push({
          path: `${path}/${key}`,
          message: `references ${reference} of level ${objectLevel} while the component declares level ${component.levelId}`,
        });
      }
    });
    // A structural member made of a material the project no longer holds is a
    // member nothing can ever check.
    (level.structure ?? []).forEach((member, index) => {
      const path = `${base}/structure/${index}`;
      if (member.levelId !== level.id)
        issues.push({
          path: `${path}/levelId`,
          message: `is stored on level ${level.id} but declares level ${member.levelId}`,
        });
      if (
        member.materialId !== undefined &&
        !(materials as ReadonlySet<string>).has(member.materialId)
      )
        issues.push({
          path: `${path}/materialId`,
          message: `references unknown material ${member.materialId}`,
        });
    });
    // A roof described by its outline stands on this storey and is built of
    // something: a build-up the project no longer holds leaves a roof whose
    // thermal behaviour nothing can answer.
    (level.roofStructures ?? []).forEach((roof, index) => {
      const path = `${base}/roofStructures/${index}`;
      if (roof.levelId !== level.id)
        issues.push({
          path: `${path}/levelId`,
          message: `is stored on level ${level.id} but declares level ${roof.levelId}`,
        });
      if (!assemblies.has(roof.assemblyId))
        issues.push({
          path: `${path}/assemblyId`,
          message: `references unknown assembly ${roof.assemblyId}`,
        });
    });
    // A stair joins two storeys; one that names a storey the project does not
    // hold is a stair whose rise nothing can answer.
    level.stairs.forEach((stair, index) => {
      const path = `${base}/stairs/${index}`;
      if (stair.levelId !== level.id)
        issues.push({
          path: `${path}/levelId`,
          message: `is stored on level ${level.id} but declares level ${stair.levelId}`,
        });
      const top = file.project.building.levels.find(
        ({ id }) => id === stair.topLevelId,
      );
      if (top === undefined)
        issues.push({
          path: `${path}/topLevelId`,
          message: `references unknown level ${stair.topLevelId}`,
        });
      // A stair climbs. The commands refuse to draw one that arrives at or
      // below the storey it leaves, but a file can be written by anything, and
      // such a stair has a rise of zero or less: its riser height, its Blondel
      // and its place in the quantities would all be answers to a question
      // that has none.
      else if (top.elevationMm <= level.elevationMm)
        issues.push({
          path: `${path}/topLevelId`,
          message: `arrives at level ${top.id}, which is not above level ${level.id}`,
        });
    });
    level.spaces.forEach((space, index) => {
      if (!levels.has(space.levelId))
        issues.push({
          path: `${base}/spaces/${index}/levelId`,
          message: `references unknown level ${space.levelId}`,
        });
      else if (space.levelId !== level.id)
        issues.push({
          path: `${base}/spaces/${index}/levelId`,
          message: `is stored on level ${level.id} but declares level ${space.levelId}`,
        });
    });
  });
  // A view names the storey it draws; a sheet names the views it lays out.
  // Either naming something absent is a drawing set nothing can print.
  file.project.drawingViews?.forEach((view, index) => {
    if (view.levelId !== undefined && !levels.has(view.levelId))
      issues.push({
        path: `/project/drawingViews/${index}/levelId`,
        message: `references unknown level ${view.levelId}`,
      });
  });
  const drawingViews = new Set(
    file.project.drawingViews?.map(({ id }) => id) ?? [],
  );
  file.project.sheets?.forEach((sheet, sheetIndex) =>
    sheet.viewports.forEach((viewport, index) => {
      if (!drawingViews.has(viewport.viewId))
        issues.push({
          path: `/project/sheets/${sheetIndex}/viewports/${index}/viewId`,
          message: `references unknown drawing view ${viewport.viewId}`,
        });
    }),
  );
  file.project.building.zones?.forEach((zone, zoneIndex) =>
    zone.spaceIds.forEach((spaceId, index) => {
      // A zone groups rooms; one that names a room the project no longer holds
      // can protect that room from deletion and never let go of it.
      if (!spaces.has(spaceId))
        issues.push({
          path: `/project/building/zones/${zoneIndex}/spaceIds/${index}`,
          message: `references unknown space ${spaceId}`,
        });
    }),
  );
  file.project.assemblies?.forEach((assembly, assemblyIndex) =>
    assembly.layers.forEach((layer, layerIndex) => {
      if (!materials.has(layer.materialId))
        issues.push({
          path: `/project/assemblies/${assemblyIndex}/layers/${layerIndex}/materialId`,
          message: `references unknown material ${layer.materialId}`,
        });
    }),
  );
  file.project.systems?.forEach((network, networkIndex) => {
    const nodeIds = new Set(network.nodes.map(({ id }) => id));
    const portIds = new Set(network.ports.map(({ id }) => id));
    network.nodes.forEach((node, nodeIndex) => {
      const path = `/project/systems/${networkIndex}/nodes/${nodeIndex}`;
      if (node.spaceId !== undefined && !spaces.has(node.spaceId))
        issues.push({
          path: `${path}/spaceId`,
          message: `references unknown space ${node.spaceId}`,
        });
      const equipmentId = (node as { readonly equipmentId?: unknown })
        .equipmentId;
      if (typeof equipmentId === 'string' && !equipment.has(equipmentId))
        issues.push({
          path: `${path}/equipmentId`,
          message: `references unknown equipment ${equipmentId}`,
        });
      const levelId = (node as { readonly levelId?: unknown }).levelId;
      if (typeof levelId === 'string' && !levels.has(levelId as never))
        issues.push({
          path: `${path}/levelId`,
          message: `references unknown level ${levelId}`,
        });
      // A node fixed to a wall, a slab or a roof follows it; fixed to nothing
      // it would be left behind by the object it was meant to sit on.
      if (node.hostObjectId !== undefined && !hosts.has(node.hostObjectId))
        issues.push({
          path: `${path}/hostObjectId`,
          message: `references unknown object ${node.hostObjectId}`,
        });
      // Each identifier can be real while the three together describe a place
      // that does not exist. A node cannot be on the ground floor and inside a
      // room upstairs, and the drawing would put it on one level while the
      // calculations read the other.
      if (typeof levelId === 'string')
        for (const [key, reference] of [
          ['spaceId', node.spaceId],
          ['hostObjectId', node.hostObjectId],
        ] as const) {
          if (reference === undefined) continue;
          const objectLevel = levelOfObject.get(reference);
          // Equipment belongs to the project rather than to a level; nothing
          // is claimed about a node hosted by one.
          if (objectLevel === undefined || objectLevel === levelId) continue;
          issues.push({
            path: `${path}/${key}`,
            message: `references ${reference} of level ${objectLevel} while the node declares level ${levelId}`,
          });
        }
      // Without a declared level, the room and the object the node is fixed to
      // still have to agree with each other.
      if (
        typeof levelId !== 'string' &&
        node.spaceId !== undefined &&
        node.hostObjectId !== undefined
      ) {
        const spaceLevel = levelOfObject.get(node.spaceId);
        const hostLevel = levelOfObject.get(node.hostObjectId);
        if (
          spaceLevel !== undefined &&
          hostLevel !== undefined &&
          spaceLevel !== hostLevel
        )
          issues.push({
            path: `${path}/hostObjectId`,
            message: `references ${node.hostObjectId} of level ${hostLevel} while the node sits in a space of level ${spaceLevel}`,
          });
      }
    });
    network.ports.forEach((port, portIndex) => {
      if (!nodeIds.has(port.nodeId))
        issues.push({
          path: `/project/systems/${networkIndex}/ports/${portIndex}/nodeId`,
          message: `references unknown network node ${port.nodeId}`,
        });
    });
    network.edges.forEach((edge, edgeIndex) => {
      for (const key of ['fromPortId', 'toPortId'] as const)
        if (!portIds.has(edge[key]))
          issues.push({
            path: `/project/systems/${networkIndex}/edges/${edgeIndex}/${key}`,
            message: `references unknown network port ${edge[key]}`,
          });
    });
  });
  return issues;
}

export function serializeProjectFile(file: unknown, indentation = 2): string {
  const issues = validateProjectFile(file);
  if (issues.length > 0) throw new ProjectSerializationError(issues);
  const validatedFile = file as ProjectFile;
  if (validatedFile.schemaVersion !== CURRENT_PROJECT_SCHEMA_VERSION)
    throw new RangeError(
      `Cannot save schema version ${validatedFile.schemaVersion}.`,
    );
  if (!Number.isInteger(indentation) || indentation < 0 || indentation > 10)
    throw new RangeError('Indentation must be an integer from 0 to 10.');
  return `${JSON.stringify(canonicalize(validatedFile), null, indentation)}\n`;
}

export class ProjectSerializationError extends Error {
  constructor(readonly issues: readonly ProjectValidationIssue[]) {
    super(issues.map(({ path, message }) => `${path}: ${message}`).join('; '));
    this.name = 'ProjectSerializationError';
  }
}

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (isRecord(value))
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, canonicalize(value[key])]),
    );
  return value;
}

function compareSemver(first: string, second: string): number {
  const left = first.split('.').map(Number);
  const right = second.split('.').map(Number);
  for (let index = 0; index < 3; index += 1) {
    const difference = left[index]! - right[index]!;
    if (difference !== 0) return difference;
  }
  return 0;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
