import type { ProjectFile } from '@house-technical-designer/core-domain';
import validateProjectSchema from './generated-project-validator.js';
import {
  DEFAULT_PROJECT_MIGRATIONS,
  runMigrationChain,
  type MigrationJournalEntry,
  type ProjectMigration,
} from './migrations.js';

export const CURRENT_PROJECT_SCHEMA_VERSION = '1.0.0';

/**
 * Bounds an imported file has to respect.
 *
 * A project file arrives from outside the application: it may be corrupt,
 * generated by another tool, or simply enormous. The limits refuse such a file
 * with a message naming what is out of bounds, rather than letting the browser
 * freeze partway through drawing it. They are deliberately far above any real
 * house — a plausible dwelling uses a fraction of a percent of them.
 */
export interface ProjectImportLimits {
  /** Size of the JSON text, in characters. */
  readonly maximumCharacters: number;
  readonly maximumLevels: number;
  readonly maximumWalls: number;
  readonly maximumOpenings: number;
  readonly maximumSpaces: number;
  readonly maximumMaterials: number;
  readonly maximumNetworkNodes: number;
  readonly maximumNetworkEdges: number;
}

export const DEFAULT_PROJECT_IMPORT_LIMITS: ProjectImportLimits = {
  maximumCharacters: 32_000_000,
  maximumLevels: 50,
  maximumWalls: 20_000,
  maximumOpenings: 20_000,
  maximumSpaces: 5_000,
  maximumMaterials: 5_000,
  maximumNetworkNodes: 50_000,
  maximumNetworkEdges: 50_000,
};

/** What exceeded its bound, so the message can name it rather than say "too big". */
export interface ProjectLimitBreach {
  readonly limit: keyof ProjectImportLimits;
  readonly label: string;
  readonly actual: number;
  readonly maximum: number;
}

export interface ProjectValidationIssue {
  readonly path: string;
  readonly message: string;
}
export type ProjectLoadResult =
  | {
      readonly status: 'OK';
      readonly file: ProjectFile;
      readonly migrationJournal: readonly MigrationJournalEntry[];
    }
  | { readonly status: 'INVALID_JSON'; readonly message: string }
  | {
      readonly status: 'INVALID_PROJECT';
      readonly issues: readonly ProjectValidationIssue[];
    }
  | {
      readonly status: 'UNSUPPORTED_FUTURE_SCHEMA';
      readonly schemaVersion: string;
    }
  | { readonly status: 'MIGRATION_ERROR'; readonly message: string }
  | { readonly status: 'TOO_LARGE'; readonly breach: ProjectLimitBreach };

export function loadProjectJson(
  source: string,
  migrations: readonly ProjectMigration[] = DEFAULT_PROJECT_MIGRATIONS,
  limits: ProjectImportLimits = DEFAULT_PROJECT_IMPORT_LIMITS,
): ProjectLoadResult {
  if (source.length > limits.maximumCharacters)
    return {
      status: 'TOO_LARGE',
      breach: {
        limit: 'maximumCharacters',
        label: 'caractères',
        actual: source.length,
        maximum: limits.maximumCharacters,
      },
    };
  let value: unknown;
  try {
    value = JSON.parse(source) as unknown;
  } catch (error: unknown) {
    return {
      status: 'INVALID_JSON',
      message: error instanceof Error ? error.message : 'Invalid JSON.',
    };
  }
  if (!isRecord(value) || typeof value.schemaVersion !== 'string') {
    const issues = validateProjectFile(value);
    return { status: 'INVALID_PROJECT', issues };
  }
  if (!/^\d+\.\d+\.\d+$/u.test(value.schemaVersion)) {
    return {
      status: 'INVALID_PROJECT',
      issues: [
        { path: '/schemaVersion', message: 'must be semantic version x.y.z' },
      ],
    };
  }
  if (compareSemver(value.schemaVersion, CURRENT_PROJECT_SCHEMA_VERSION) > 0) {
    return {
      status: 'UNSUPPORTED_FUTURE_SCHEMA',
      schemaVersion: value.schemaVersion,
    };
  }
  let migrationJournal: readonly MigrationJournalEntry[] = [];
  if (value.schemaVersion !== CURRENT_PROJECT_SCHEMA_VERSION) {
    const migrated = runMigrationChain(
      value,
      CURRENT_PROJECT_SCHEMA_VERSION,
      migrations,
    );
    if (migrated.status !== 'OK') {
      return {
        status: 'MIGRATION_ERROR',
        message:
          migrated.status === 'MIGRATION_NOT_FOUND'
            ? `No migration path from ${migrated.from} to ${migrated.target}.`
            : `${migrated.migrationId}: ${migrated.message}`,
      };
    }
    value = migrated.value;
    migrationJournal = migrated.journal;
  }
  const issues = validateProjectFile(value);
  if (issues.length > 0) return { status: 'INVALID_PROJECT', issues };
  const file = value as ProjectFile;
  const breach = exceededLimit(file, limits);
  if (breach !== undefined) return { status: 'TOO_LARGE', breach };
  return { status: 'OK', file: structuredClone(file), migrationJournal };
}

/** The first bound the file exceeds, counted on the validated model. */
export function exceededLimit(
  file: ProjectFile,
  limits: ProjectImportLimits = DEFAULT_PROJECT_IMPORT_LIMITS,
): ProjectLimitBreach | undefined {
  const levels = file.project.building.levels;
  const networks = file.project.systems ?? [];
  const counts: readonly {
    readonly limit: keyof ProjectImportLimits;
    readonly label: string;
    readonly actual: number;
  }[] = [
    { limit: 'maximumLevels', label: 'niveaux', actual: levels.length },
    {
      limit: 'maximumWalls',
      label: 'murs',
      actual: total(levels, ({ walls }) => walls.length),
    },
    {
      limit: 'maximumOpenings',
      label: 'ouvertures',
      actual: total(levels, ({ openings }) => openings.length),
    },
    {
      limit: 'maximumSpaces',
      label: 'pièces',
      actual: total(levels, ({ spaces }) => spaces.length),
    },
    {
      limit: 'maximumMaterials',
      label: 'matériaux',
      actual: file.project.materialLibrary?.materials.length ?? 0,
    },
    {
      limit: 'maximumNetworkNodes',
      label: 'nœuds de réseau',
      actual: total(networks, ({ nodes }) => nodes.length),
    },
    {
      limit: 'maximumNetworkEdges',
      label: 'tronçons de réseau',
      actual: total(networks, ({ edges }) => edges.length),
    },
  ];
  for (const count of counts) {
    const maximum = limits[count.limit];
    if (count.actual > maximum) return { ...count, maximum };
  }
  return undefined;
}

function total<T>(items: readonly T[], size: (item: T) => number): number {
  return items.reduce((sum, item) => sum + size(item), 0);
}

/** Validates with the compiled canonical JSON Schema, then checks project-wide references. */
export function validateProjectFile(
  value: unknown,
): readonly ProjectValidationIssue[] {
  if (!validateProjectSchema(value))
    return (validateProjectSchema.errors ?? []).map((error) => ({
      path:
        error.keyword === 'required' &&
        typeof error.params.missingProperty === 'string'
          ? `${error.instancePath}/${error.params.missingProperty}`
          : error.instancePath === ''
            ? '/'
            : error.instancePath,
      message: error.message ?? 'does not satisfy the project schema',
    }));
  return validateProjectReferences(value as ProjectFile);
}

/**
 * References and containment, checked across the whole project.
 *
 * A reference that names something absent is a broken file; so is an object
 * stored in a container it does not belong to. An opening whose wall exists on
 * another level passes a "the wall exists" test and still describes a house
 * nobody can build, so containment is checked, not only existence.
 */
export function validateProjectReferences(
  file: ProjectFile,
): readonly ProjectValidationIssue[] {
  const issues: ProjectValidationIssue[] = [];
  const levels = new Set(file.project.building.levels.map(({ id }) => id));
  const walls = new Set(
    file.project.building.levels.flatMap(({ walls }) =>
      walls.map(({ id }) => id),
    ),
  );
  const spaces = new Set<string>(
    file.project.building.levels.flatMap(({ spaces }) =>
      spaces.map(({ id }) => id as string),
    ),
  );
  const equipment = new Set(file.project.equipment?.map(({ id }) => id) ?? []);
  for (const [what, ids] of [
    ['level', file.project.building.levels.map(({ id }) => id)],
    [
      'wall',
      file.project.building.levels.flatMap(({ walls }) =>
        walls.map(({ id }) => id),
      ),
    ],
    [
      'space',
      file.project.building.levels.flatMap(({ spaces }) =>
        spaces.map(({ id }) => id),
      ),
    ],
    ['assembly', file.project.assemblies?.map(({ id }) => id) ?? []],
    [
      'material',
      file.project.materialLibrary?.materials.map(({ id }) => id) ?? [],
    ],
    ['equipment', file.project.equipment?.map(({ id }) => id) ?? []],
    ['network', file.project.systems?.map(({ id }) => id) ?? []],
  ] as const)
    for (const duplicate of repeated(ids))
      issues.push({
        path: `/project/${what}s`,
        message: `declares ${what} ${duplicate} more than once`,
      });
  const materials = new Set(
    file.project.materialLibrary?.materials.map(({ id }) => id) ?? [],
  );
  const assemblies = new Set(
    file.project.assemblies?.map(({ id }) => id) ?? [],
  );
  file.project.building.levels.forEach((level, levelIndex) => {
    const base = `/project/building/levels/${levelIndex}`;
    const levelWalls = new Set(level.walls.map(({ id }) => id));
    for (const [collection, elements] of [
      ['walls', level.walls],
      ['slabs', level.slabs],
      ['roofs', level.roofs],
    ] as const)
      elements.forEach((element, index) => {
        if (!levels.has(element.levelId))
          issues.push({
            path: `${base}/${collection}/${index}/levelId`,
            message: `references unknown level ${element.levelId}`,
          });
        else if (element.levelId !== level.id)
          issues.push({
            path: `${base}/${collection}/${index}/levelId`,
            message: `is stored on level ${level.id} but declares level ${element.levelId}`,
          });
        if (!assemblies.has(element.assemblyId))
          issues.push({
            path: `${base}/${collection}/${index}/assemblyId`,
            message: `references unknown assembly ${element.assemblyId}`,
          });
      });
    level.openings.forEach((opening, index) => {
      if (!walls.has(opening.hostElementId))
        issues.push({
          path: `${base}/openings/${index}/hostElementId`,
          message: `references unknown wall ${opening.hostElementId}`,
        });
      else if (!levelWalls.has(opening.hostElementId))
        issues.push({
          path: `${base}/openings/${index}/hostElementId`,
          message: `is stored on level ${level.id} but hosted by wall ${opening.hostElementId} of another level`,
        });
    });
    level.spaces.forEach((space, index) => {
      if (!levels.has(space.levelId))
        issues.push({
          path: `${base}/spaces/${index}/levelId`,
          message: `references unknown level ${space.levelId}`,
        });
      else if (space.levelId !== level.id)
        issues.push({
          path: `${base}/spaces/${index}/levelId`,
          message: `is stored on level ${level.id} but declares level ${space.levelId}`,
        });
    });
  });
  file.project.assemblies?.forEach((assembly, assemblyIndex) =>
    assembly.layers.forEach((layer, layerIndex) => {
      if (!materials.has(layer.materialId))
        issues.push({
          path: `/project/assemblies/${assemblyIndex}/layers/${layerIndex}/materialId`,
          message: `references unknown material ${layer.materialId}`,
        });
    }),
  );
  file.project.systems?.forEach((network, networkIndex) => {
    const nodeIds = new Set(network.nodes.map(({ id }) => id));
    const portIds = new Set(network.ports.map(({ id }) => id));
    network.nodes.forEach((node, nodeIndex) => {
      const path = `/project/systems/${networkIndex}/nodes/${nodeIndex}`;
      if (node.spaceId !== undefined && !spaces.has(node.spaceId))
        issues.push({
          path: `${path}/spaceId`,
          message: `references unknown space ${node.spaceId}`,
        });
      const equipmentId = (node as { readonly equipmentId?: unknown })
        .equipmentId;
      if (typeof equipmentId === 'string' && !equipment.has(equipmentId))
        issues.push({
          path: `${path}/equipmentId`,
          message: `references unknown equipment ${equipmentId}`,
        });
    });
    network.ports.forEach((port, portIndex) => {
      if (!nodeIds.has(port.nodeId))
        issues.push({
          path: `/project/systems/${networkIndex}/ports/${portIndex}/nodeId`,
          message: `references unknown network node ${port.nodeId}`,
        });
    });
    network.edges.forEach((edge, edgeIndex) => {
      for (const key of ['fromPortId', 'toPortId'] as const)
        if (!portIds.has(edge[key]))
          issues.push({
            path: `/project/systems/${networkIndex}/edges/${edgeIndex}/${key}`,
            message: `references unknown network port ${edge[key]}`,
          });
    });
  });
  return issues;
}

/** Identifiers a list declares more than once. */
function repeated(ids: readonly string[]): readonly string[] {
  const seen = new Set<string>();
  const twice = new Set<string>();
  for (const id of ids) {
    if (seen.has(id)) twice.add(id);
    seen.add(id);
  }
  return [...twice];
}

export function serializeProjectFile(file: unknown, indentation = 2): string {
  const issues = validateProjectFile(file);
  if (issues.length > 0) throw new ProjectSerializationError(issues);
  const validatedFile = file as ProjectFile;
  if (validatedFile.schemaVersion !== CURRENT_PROJECT_SCHEMA_VERSION)
    throw new RangeError(
      `Cannot save schema version ${validatedFile.schemaVersion}.`,
    );
  if (!Number.isInteger(indentation) || indentation < 0 || indentation > 10)
    throw new RangeError('Indentation must be an integer from 0 to 10.');
  return `${JSON.stringify(canonicalize(validatedFile), null, indentation)}\n`;
}

export class ProjectSerializationError extends Error {
  constructor(readonly issues: readonly ProjectValidationIssue[]) {
    super(issues.map(({ path, message }) => `${path}: ${message}`).join('; '));
    this.name = 'ProjectSerializationError';
  }
}

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (isRecord(value))
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, canonicalize(value[key])]),
    );
  return value;
}

function compareSemver(first: string, second: string): number {
  const left = first.split('.').map(Number);
  const right = second.split('.').map(Number);
  for (let index = 0; index < 3; index += 1) {
    const difference = left[index]! - right[index]!;
    if (difference !== 0) return difference;
  }
  return 0;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
