import type { DataRegistry } from '@house-technical-designer/technical-types';
import { rawGenericEquipmentEntries } from '@house-technical-designer/equipment-catalog';
import { rawGenericMaterialEntries } from '@house-technical-designer/materials';
import { rawGenericAssemblyEntries } from '@house-technical-designer/assemblies';
import { rawGenericOpeningEntries } from '@house-technical-designer/opening-catalog';
import { NETWORK_PRODUCT_REGISTRY } from '@house-technical-designer/network-products';
import { rawGenericSymbolEntries } from '@house-technical-designer/drawing-engine';
import recorded from '../data/fingerprints.json' with { type: 'json' };
import { contentFingerprint } from './catalog-validation.js';
import { formatCatalogRef, type CatalogRef } from './catalog-identity.js';

/**
 * One entry of any registry, seen as « a thing with an identity and a body ».
 *
 * The promise a version makes does not care which registry the entry is in:
 * `MATERIAL:generic-rock-wool@1.0.0` has to mean the same figures today as it
 * did when a project pinned it, exactly as `EQUIPMENT:generic-battery@1.0.0`
 * does. Only the equipment catalogue was protected, so a correction to the
 * rock wool would have reached every wall already drawn with it, silently.
 */
interface StampedEntry {
  readonly ref: CatalogRef;
  readonly body: unknown;
}

function stamped(
  registry: DataRegistry,
  entries: readonly {
    readonly id: string;
    readonly version?: string;
  }[],
): readonly StampedEntry[] {
  return entries.map((entry) => {
    const { id: _id, version: _version, ...body } = entry;
    return {
      ref: { registry, id: entry.id, version: entry.version ?? '' },
      body,
    };
  });
}

/** Every entry the application ships, whichever registry it belongs to. */
export function stampedCatalogEntries(): readonly StampedEntry[] {
  return [
    ...stamped('EQUIPMENT', rawGenericEquipmentEntries()),
    ...stamped('MATERIAL', rawGenericMaterialEntries()),
    ...stamped('OPENING', rawGenericOpeningEntries()),
    ...stamped('ASSEMBLY', rawGenericAssemblyEntries()),
    ...stamped('NETWORK_PRODUCT', NETWORK_PRODUCT_REGISTRY),
    ...stamped('SYMBOL', rawGenericSymbolEntries()),
  ];
}

/**
 * What every entry of every registry says right now, keyed by its reference.
 *
 * `EQUIPMENT:generic-air-water-heat-pump@1.1.0`, and not
 * `generic-air-water-heat-pump@1.1.0`: two registries may hold the same
 * identifier — a symbol and an equipment can both be called
 * `generic-heat-pump` — and a key that cannot tell them apart is a key that
 * would let one of them inherit the other's promise.
 */
export function catalogFingerprints(): Readonly<Record<string, string>> {
  return Object.fromEntries(
    stampedCatalogEntries()
      .map(({ ref, body }): readonly [string, string] => [
        formatCatalogRef(ref),
        contentFingerprint(body),
      ])
      .sort(([first], [second]) => first.localeCompare(second)),
  );
}

/**
 * What each catalogue entry said when its version was fixed.
 *
 * Data rather than code: it is regenerated by a script and read by a gate, and
 * nobody is meant to reason about it.
 */
export const CATALOG_FINGERPRINTS: Readonly<Record<string, string>> = (
  recorded as { readonly entries: Readonly<Record<string, string>> }
).entries;

export interface FingerprintIssue {
  readonly ref: string;
  readonly message: string;
}

/**
 * Everything the version promise no longer covers, across all six registries.
 *
 * Three ways it can be broken, and all three used to be possible outside the
 * equipment catalogue: a fiche nobody recorded, so the promise never applied
 * to it; a fiche whose content moved while its version stood still, which is
 * the silent correction the whole mechanism exists to refuse; and a record for
 * an entry nothing ships any more, which the next entry to take that
 * identifier would inherit.
 */
export function validateCatalogFingerprints(
  stamps: Readonly<Record<string, string>> = CATALOG_FINGERPRINTS,
): readonly FingerprintIssue[] {
  const issues: FingerprintIssue[] = [];
  const shipped = new Set<string>();
  for (const { ref, body } of stampedCatalogEntries()) {
    const key = formatCatalogRef(ref);
    shipped.add(key);
    const stamp = stamps[key];
    if (stamp === undefined)
      issues.push({
        ref: key,
        message:
          'is not recorded: it has no fingerprint. Run npm run catalog:fingerprints.',
      });
    else if (stamp !== contentFingerprint(body))
      issues.push({
        ref: key,
        message:
          'has changed without its version changing: it no longer says what it said. Raise the version, then run npm run catalog:fingerprints.',
      });
  }
  for (const key of Object.keys(stamps))
    if (!shipped.has(key))
      issues.push({
        ref: key,
        message:
          'is recorded and no entry claims it. Run npm run catalog:fingerprints.',
      });
  return issues;
}
